version: '3.8'

services:
  github-pages:
    image: jekyll/jekyll:latest
    command: jekyll serve --livereload --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
      - "35729:35729" # Required for LiveReload to connect properly
    volumes:
      - .:/srv/jekyll:Z
    environment:
      - JEKYLL_ENV=development
